"""Teste

Revision ID: 29c983af6036
Revises: e581c02de294
Create Date: 2023-05-29 00:27:03.895901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c983af6036'
down_revision = 'e581c02de294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instituicao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'periodo', ['periodo_id'], ['id'])
        batch_op.create_foreign_key(None, 'instituicao', ['instituicao_id'], ['id'])

    with op.batch_alter_table('alunogrupo', schema=None) as batch_op:
        batch_op.alter_column('aluno_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('grupo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('coordenador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instituicao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'instituicao', ['instituicao_id'], ['id'])

    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_constraint('curso_instituicao_id_fkey', type_='foreignkey')
        batch_op.drop_column('instituicao_id')

    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semestreturma', sa.Integer(), nullable=False))
        batch_op.alter_column('coordenador_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('instituicao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('curso_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'curso', ['curso_id'], ['id'])
        batch_op.create_foreign_key(None, 'endereco', ['endereco_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instituicao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('curso_id')
        batch_op.drop_column('endereco_id')

    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.alter_column('coordenador_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('semestreturma')

    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instituicao_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('curso_instituicao_id_fkey', 'instituicao', ['instituicao_id'], ['id'])

    with op.batch_alter_table('coordenador', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('instituicao_id')

    with op.batch_alter_table('alunogrupo', schema=None) as batch_op:
        batch_op.alter_column('grupo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('aluno_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('instituicao_id')
        batch_op.drop_column('periodo_id')

    # ### end Alembic commands ###
