"""Tabelas e Recursos

Revision ID: e581c02de294
Revises: 
Create Date: 2023-05-29 00:17:59.805740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e581c02de294'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestrereferencia', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alunogrupo', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'aluno', ['aluno_id'], ['id'])

    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'aluno', ['aluno_id'], ['id'])
        batch_op.create_foreign_key(None, 'periodo', ['periodo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('alunogrupo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('periodo')
    op.drop_table('aluno')
    # ### end Alembic commands ###
